### ISSUE TITLE
Please, drop Target Mapping from More help on  integrating Adobe Target with Adobe Campaign

### ISSUE THREAD

**Issue by dburwitz** [AdobeDocs/campaign-classic-learn.en#2]
Issue in ./help/integrations/target-integration.md

The last section **More help on this feature** lists 3 topics. Of which the 3rd [Target mapping](https://experienceleague.adobe.com/docs/campaign-classic/using/configuring-campaign-classic/use-a-custom-recipient-table/target-mapping.html?lang=en) is irrelevant to integrating Adobe Target with Adobe Campaign. 
Please, remove this 3rd topic. The first 2 topics are spot on.

The full topic list:
[Configure the integration with Adobe Target](https://experienceleague.adobe.com/docs/campaign-classic/using/integrating-with-adobe-experience-cloud/adobe-target/configuring-the-integration-with-adobe-target.html?lang=en)
[Work with Campaign and Target](https://experienceleague.adobe.com/docs/campaign-classic/using/integrating-with-adobe-experience-cloud/adobe-target/integrating-with-adobe-target.html?lang=en)
[Target mapping](https://experienceleague.adobe.com/docs/campaign-classic/using/configuring-campaign-classic/use-a-custom-recipient-table/target-mapping.html?lang=en)

**Comment by sanhaus** [comment]
@dburwitz, thank you for the feedback, that is very helpful. The suggested content is autogenerated based on multiple criteria. 

@dwright-adobe, the last link is pointing to a documentation page that is not related to the target integration is there anything we can do to make sure that the page isn't suggested in the Adobe Target integration context?

**Comment by dwright-adobe** [comment]
I think we resolved this issue. The links I see now are:
More help on this feature
[Work with Campaign and Target](https://experienceleague.adobe.com/docs/campaign-classic/using/integrating-with-adobe-experience-cloud/adobe-target/integrating-with-adobe-target.html?lang=en)
[Configure the integration with Adobe Target](https://experienceleague.adobe.com/docs/campaign-classic/using/integrating-with-adobe-experience-cloud/adobe-target/configuring-the-integration-with-adobe-target.html?lang=en)
[Insert Target dynamic content](https://experienceleague.adobe.com/docs/campaign-classic/using/integrating-with-adobe-experience-cloud/adobe-target/inserting-a-dynamic-image.html?lang=en)
